version: '3.7'

services:
  app:
    container_name: vinopinions-notification-service_devcontainer-app
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - .env
    volumes:
      - ..:/workspace
    user: dev

  db:
    container_name: vinopinions-notification-service_devcontainer-db
    image: mongo:7
    hostname: ${MONGO_HOSTNAME}
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo-data:/data/db

  redis:
    container_name: vinopinions-notification-service_devcontainer-redis
    hostname: ${REDIS_HOSTNAME}
    image: redis/redis-stack:7.2.0-v10
    ports:
      - ${REDIS_UI_PORT}:8001
      - ${REDIS_PORT}:6379
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
