version: '3.7'

services:
  app:
    container_name: notification-service_devcontainer-app
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - .env
    volumes:
      - ..:/workspace
    user: dev

  db:
    container_name: notification-service_devcontainer-db
    image: postgres:16
    hostname: ${POSTGRES_HOSTNAME}
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    container_name: notification-service_devcontainer-redis
    hostname: ${REDIS_HOSTNAME}
    image: redis/redis-stack:7.2.0-v10
    ports:
      - ${REDIS_UI_PORT}:8001
      - ${REDIS_PORT}:6379
    volumes:
      - redis-data:/data

volumes:
  pg-data:
  redis-data:
