name: Unit Test

on:
  pull_request:
    branches: ['developer', 'master']
  workflow_call:
  schedule:
    - cron: '0 8 * * *'

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup yarn
        uses: ./.github/actions/setup-yarn
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install dependencies
        run: yarn --immutable

      - name: Run Tests
        run: yarn test --ci
        env:
          NODE_ENV: ${{ vars.NODE_ENV }}
