inputs:
  node-version:
    description: 'The version of Node.js to use'
    required: false
    default: 'current'

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - run: corepack enable
      shell: bash
